theme: jekyll-theme-minimal
title: UNIQUE Community Calendar
description: >
            A community-powered tool to gather Quebec-based events
            at the intersection of neuroscience and AI.
logo: https://raw.githubusercontent.com/emdupre/UNIQUE-Community-Calendar/master/logos/logo.png