theme: jekyll-theme-minimal
title: UNIQUE Community Calendar
description: >
            A community tool to gather Quebec-based events
            at the intersection of neuroscience and AI.
logo: https://raw.githubusercontent.com/emdupre/UNIQUE-Community-Calendar/master/Documents/Images/unique-comm-cal.png